import { chromium } from 'playwright-core';
const API='http://127.0.0.1:41185', TOKEN='scratchtesttoken0001';
const api=async(m,p,b)=>{const r=await fetch(`${API}${p}${p.includes('?')?'&':'?'}token=${TOKEN}`,{method:m,body:b?JSON.stringify(b):undefined});if(!r.ok)throw new Error(await r.text());return r.json();};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const browser=await chromium.connectOverCDP('http://127.0.0.1:9337');
const page=browser.contexts()[0].pages().find(p=>p.url().includes('/index.html'));
await page.bringToFront();
const folder=await api('POST','/folders',{title:'FL '+Date.now()});
const note=await api('POST','/notes',{title:'flow',body:'MARK\n\n- one\n- two',parent_id:folder.id});
const decoy=await api('POST','/notes',{title:'decoy',body:'MARK decoy',parent_id:folder.id});
await sleep(1500);
await page.getByText(folder.title,{exact:true}).first().click();
const open=async(t)=>{await page.getByText(t,{exact:true}).first().click();await page.waitForFunction(()=>{const ed=window.tinymce&&window.tinymce.activeEditor;return ed&&ed.getBody().textContent.includes('MARK')&&ed.__keepBlankBullets===true;},null,{timeout:15000});await sleep(1200);};
const body=async()=>(await api('GET',`/notes/${note.id}?fields=body`)).body;
const lis=()=>page.evaluate(()=>[...window.tinymce.activeEditor.getBody().querySelectorAll('li')].map(l=>JSON.stringify(l.textContent)).join(','));
await open('flow');
await page.evaluate(()=>{const ed=window.tinymce.activeEditor;ed.focus();const l=ed.getBody().querySelectorAll('li');ed.selection.select(l[l.length-1],true);ed.selection.collapse(false);});
await page.keyboard.press('Enter'); await sleep(3000);
console.log('1 after Enter      saved',JSON.stringify(await body()),'| dom',await lis());
// external change while idle on the blank bullet = forced redraw from saved Markdown
await api('PUT',`/notes/${note.id}`,{body:(await body()).replace('MARK','MARK edited elsewhere')}); await sleep(3000);
console.log('2 after ext redraw saved',JSON.stringify(await body()),'| dom',await lis());
const where=await page.evaluate(()=>{const ed=window.tinymce.activeEditor;const n=ed.selection.getNode();return n.nodeName+':'+JSON.stringify(n.textContent);});
console.log('  cursor now in',where);
await open('decoy'); await open('flow');
console.log('3 after reopen     saved',JSON.stringify(await body()),'| dom',await lis());
await page.evaluate(()=>{const ed=window.tinymce.activeEditor;ed.focus();const l=ed.getBody().querySelectorAll('li');ed.selection.setCursorLocation(l[l.length-1],0);});
await page.keyboard.type('three'); await sleep(3000);
const b=await body();
console.log('4 after typing     saved',JSON.stringify(b),'| dom',await lis(),'| nbsp left:',/&nbsp;| /.test(b));
await page.keyboard.press('Enter'); await sleep(400); await page.keyboard.press('Enter'); await sleep(3000);
console.log('5 Enter twice (exit list) saved',JSON.stringify(await body()),'| dom',await lis());
await page.keyboard.press('Control+z');await sleep(300);await page.keyboard.press('Control+z'); await sleep(3000);
console.log('6 undo x2          saved',JSON.stringify(await body()),'| dom',await lis());
await browser.close().catch(()=>{});process.exit(0);
